#コンテキストパス設定
server.servlet.context-path=/practice
#ポート番号
server.port=5555
#キャッシュ無効
spring.thymeleaf.cache=false

#DB接続
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=spring_practice
spring.datasource.password=systemsss

#コンソールに実行されたSQLを表示
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#日付形式指定
spring.mvc.format.date=yyyy/MM/dd